title: "Hi, I'm Andreas"
email: andreas@willich.io

baseurl: ""
url: "https://willich.io/"
theme: minima
paginate: 10
paginate_path: "blog"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author
author: "Andreas Willich"

# Taxonomies
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Navigation menu (for use in layouts)
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Blog"
      url: "/blog/"
      weight: 3

# Enable robots.txt
robots: true
