baseURL = "https://willich.io/"
languageCode = "en-us"
title = "Hi, I'm Andreas"
theme = "hugo-bootstrap"

# Pagination
paginate = 3
paginatePath = "blog"

#pygmentsUseClasses=true

[taxonomies]
  tag = "tags"
  category = "categories"

enableRobotsTXT = true

# [params.social]
#   	twitter = "sabotageandi"
#   	github = "sabotageandi"

# Main Menu
[[menu.main]]
	name = "Home"
	weight = 1
	url = "/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 3
    identifier = "posts"
    url = "/blog/"
[[menu.main]]
    name = "Speaking"
    weight = 4
    url = "/speaking/"



[params]
  # Main sections (currently used for the recent posts in the sidebar)
  #mainSections = ["blog"]

    # Default author
  author = "Andreas Willich"

  # Date format (default: Jan 2, 2006)
  # date_format = "Jan 2, 2006"

  # Display post summaries instead of content in list templates (default: true)
  truncate = false

  [params.sidebar]
    # Whether to show the recent posts or not (default: true)
    showRecent = false

    # Whether to show the taxonomies or not (default: true)
    # showTaxonomy = false

    # How many posts to show on the sidebar (Default: 5)
    # num_recent_posts = 5

[permalinks]
  blog = "/:year/:month/:day/:slug/"